logging:
  level:
    root: INFO
    application: DEBUG

management:
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
    access:
      default: none
      max-permitted: read_only
  server:
    port: 8081

server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: dummy
    password: dummy
    url: jdbc:postgresql://localhost:5432/backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER:dummy-issuer}
          jwk-set-uri: ${JWKS_URI:https://localhost/dummy-issuer/JWKS}
