name: build-angular

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory to use."
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

      - run: npx playwright install --with-deps chromium

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run e2e
